
package br.com.fiap.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ArquivoWebService", targetNamespace = "http://exemplos.ws.fiap.com/", wsdlLocation = "http://desktop-mf56310:8080/WSAnexos/ArquivoWebService?wsdl")
public class ArquivoWebService
    extends Service
{

    private final static URL ARQUIVOWEBSERVICE_WSDL_LOCATION;
    private final static WebServiceException ARQUIVOWEBSERVICE_EXCEPTION;
    private final static QName ARQUIVOWEBSERVICE_QNAME = new QName("http://exemplos.ws.fiap.com/", "ArquivoWebService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://desktop-mf56310:8080/WSAnexos/ArquivoWebService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ARQUIVOWEBSERVICE_WSDL_LOCATION = url;
        ARQUIVOWEBSERVICE_EXCEPTION = e;
    }

    public ArquivoWebService() {
        super(__getWsdlLocation(), ARQUIVOWEBSERVICE_QNAME);
    }

    public ArquivoWebService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ARQUIVOWEBSERVICE_QNAME, features);
    }

    public ArquivoWebService(URL wsdlLocation) {
        super(wsdlLocation, ARQUIVOWEBSERVICE_QNAME);
    }

    public ArquivoWebService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ARQUIVOWEBSERVICE_QNAME, features);
    }

    public ArquivoWebService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ArquivoWebService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ArquivoWeb
     */
    @WebEndpoint(name = "ArquivoWebPort")
    public ArquivoWeb getArquivoWebPort() {
        return super.getPort(new QName("http://exemplos.ws.fiap.com/", "ArquivoWebPort"), ArquivoWeb.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ArquivoWeb
     */
    @WebEndpoint(name = "ArquivoWebPort")
    public ArquivoWeb getArquivoWebPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://exemplos.ws.fiap.com/", "ArquivoWebPort"), ArquivoWeb.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ARQUIVOWEBSERVICE_EXCEPTION!= null) {
            throw ARQUIVOWEBSERVICE_EXCEPTION;
        }
        return ARQUIVOWEBSERVICE_WSDL_LOCATION;
    }

}
