
package br.com.fiap.exemplo.ws.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "HelloWebService", targetNamespace = "http://ws.exemplo.fiap.com.br/", wsdlLocation = "http://localhost:8080/hello?wsdl")
public class HelloWebService
    extends Service
{

    private final static URL HELLOWEBSERVICE_WSDL_LOCATION;
    private final static WebServiceException HELLOWEBSERVICE_EXCEPTION;
    private final static QName HELLOWEBSERVICE_QNAME = new QName("http://ws.exemplo.fiap.com.br/", "HelloWebService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/hello?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        HELLOWEBSERVICE_WSDL_LOCATION = url;
        HELLOWEBSERVICE_EXCEPTION = e;
    }

    public HelloWebService() {
        super(__getWsdlLocation(), HELLOWEBSERVICE_QNAME);
    }

    public HelloWebService(WebServiceFeature... features) {
        super(__getWsdlLocation(), HELLOWEBSERVICE_QNAME, features);
    }

    public HelloWebService(URL wsdlLocation) {
        super(wsdlLocation, HELLOWEBSERVICE_QNAME);
    }

    public HelloWebService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, HELLOWEBSERVICE_QNAME, features);
    }

    public HelloWebService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HelloWebService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns HelloWeb
     */
    @WebEndpoint(name = "HelloWebPort")
    public HelloWeb getHelloWebPort() {
        return super.getPort(new QName("http://ws.exemplo.fiap.com.br/", "HelloWebPort"), HelloWeb.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HelloWeb
     */
    @WebEndpoint(name = "HelloWebPort")
    public HelloWeb getHelloWebPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.exemplo.fiap.com.br/", "HelloWebPort"), HelloWeb.class, features);
    }

    private static URL __getWsdlLocation() {
        if (HELLOWEBSERVICE_EXCEPTION!= null) {
            throw HELLOWEBSERVICE_EXCEPTION;
        }
        return HELLOWEBSERVICE_WSDL_LOCATION;
    }

}
